package com.example.grocery;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import java.util.TimeZone;

public class Order implements Comparable<Order> {
    private int id;
    private String customer_name;
    private int customer_id;
    private long time;
    private int status; //0 created, 1 completed, 2 picked up (optional)
    //	[{product_id: product1_id, quantity: 3}, 1:{},...]
    private ArrayList<Map<String, Integer>> products_data;

    public Order() {
    }
    public Order(String customer_name, int customer_id, ArrayList<Map<String, Integer>> products_data) {
        this.customer_name = customer_name;
        this.customer_id = customer_id;
        this.products_data = products_data;
        this.time = new Date().getTime(); //number of milliseconds Jan 1 UTC
        // id is generated by a combination of milliseconds and the customer id (unique to email)
        this.id = (int)(this.time % 100000 + 100000*customer_id);
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCustomer_name() {
        return customer_name;
    }

    public void setCustomer_name(String customer_name) {
        this.customer_name = customer_name;
    }

    public int getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(int customer_id) {
        this.customer_id = customer_id;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public ArrayList<Map<String, Integer>> getProducts_data() {
        return products_data;
    }

    public void setProducts_data(ArrayList<Map<String, Integer>> products_data) {
        this.products_data = products_data;
    }

    @Override
    public int compareTo(Order o) {
        return Long.compare(o.getTime(), this.time);
    }

    public String getTimeFormatted() {
        Date date = new Date(this.time);
        DateFormat deviceFormat = new SimpleDateFormat("yyyy/MM/dd  h:mm: a");
        deviceFormat.setTimeZone(TimeZone.getDefault()); //Device timezone
        return deviceFormat.format(date);
    }
}
